docs/topics/accounts/ibans/index.mdx

This is a small update for the changelog. Partners can now add virtual IBANs from the dashboard.

DOC-929 add virtual IBANs to dashboard

---

changelog/2025/2025-03-27.mdx
changelog/coming-up.mdx

Pre-approved changelog items for this week.

27 March 2025 Changelog

---

docs/topics/onboarding/company/index.mdx
docs/topics/users/identifications/index.mdx

I updated the recommended identification levels for Italy.

DOC-993 update to the Italian identification levels

---

docs/topics/accounts/index.mdx

Updated across our various resources too. 
[Support Center](https://support.swan.io/hc/en-150/articles/16464971717277/live_preview/01JQ6CRPBQ4VAW699FNKGR315D)
Swan Academy - ![Screenshot 2025-03-25 at 11 16 48](https://github.com/user-attachments/assets/5eb0435e-aff3-4df6-877f-892b56ca7e80)

Doc 912 update account balance formula

---

docs/topics/projects/index.mdx

I added two text message notifications and a new table for email notifications. Content has been reviewed and validated by Karine.

DOC-928 New text message and email notifications

---

docs/developers/using-api/webhooks.mdx

Added missing merchant payments webhook event: 
`MerchantPayment.Disputed` | Merchant payment was disputed

DOC-1017 Webhooks-added MerchantPayment.Disputed

---

docs/topics/merchants/online/sdd/guide-initiate.mdx

The initiateMerchantPaymentCollection mutation has been deprecated in favour of initiateSepaDirectDebitMerchantPayment. 
- Updated the mutation in API explorer
Guide:
- Updated steps 2 and 4 of the guide
- Updated the link in the guide
- Updated the mutation in the guide

DOC-1007 Update to Initiate a SEPA Direct Debit transaction mutation

---

docs/topics/cards/physical/index.mdx

The readability level is a bit higher due to the code and technical jargon. Can't find a way around it without losing meaning for the developers.

DOC-1034 Selecting shipping methods

---

changelog/2025/2025-04-24.mdx
changelog/coming-up.mdx
docs/topics/cards/physical/index.mdx

We're missing links for the changelog items - will add them after final updates.

Changelog 24  April 2025

---

docs/topics/accounts/funding/index.mdx
docs/topics/partials/_sdd-booked.mdx

Updated the booked and settlement times for SDD core and B2B.

DOC-1047 Settlement & Booked Times

---

changelog/2025/2025-05-07.mdx
changelog/coming-up.mdx

Hey,
I tried to reduce the reading level as much as possible, but again, some details are required; otherwise, it wouldn't make sense.

DOC-1051 7 May Changelog

---

docs/topics/merchants/online/cards/guide-create-link.mdx
docs/topics/merchants/online/cards/index.mdx
docs/topics/merchants/online/cards/sandbox.mdx
docs/topics/merchants/partials/_guide-request-steps.mdx
docs/topics/merchants/partials/_webhooks.mdx

Content is ready for review.
I'll probably add links to rolling reserve and payment amount limit after.

DOC-1025 Accepting card payments updates

---

docs/topics/payments/overview/guide-get-transaction-info.mdx

I just need to:
- Update the sentence about filtering, I said for `Booked` it should be `status`
- Update the payload to show the IBAN, BIC etc.

DOC-1071 New transactions filters

---

docs/partnership/document-center/proof-address/index.mdx

Added to the table: [Linear ticket](https://linear.app/swan/issue/DOC-1066/mobile-phone-bills-as-proof-of-address)

doc-1066-mobile-phone-bills-as-proof-of-address

---

changelog/coming-up.mdx

Added the two upcoming breaking changes to the callout at the top. 
Same content.

breaking change addtions

---

docs/partnership/document-center/company-registration/germany.mdx
docs/partnership/document-center/company-registration/spain.mdx
docs/partnership/document-center/partials/_intro-registration.mdx

Not ready for review - I just need a preview.

DOC-1046 Spain Proof of Reg

---

docs/partnership/document-center/company-registration/france.mdx
docs/partnership/document-center/company-registration/germany.mdx
docs/partnership/document-center/company-registration/spain.mdx
docs/partnership/document-center/partials/_intro-registration.mdx

Updates:
Added the mandatory documents callout at the top of the page. 
I removed the callouts between each section for France, Spain, and Germany because they were repetitive. 
Thanks!

Updates to POR docs

---

docs/topics/cards/physical/guide-cancel.mdx

Hey,
Added the guide, mutation and payload. 
I left the section about "Lost or stolen cards" in case you want to keep it. I'm not sure it makes sense, but maybe we'll need to confirm with someone from Product. I left a comment about that on Notion, and I'm happy to discuss it.

Doc 702/update cancel physical card

---

docs/topics/cards/physical/guide-renew.mdx
docs/topics/cards/physical/index.mdx
sidebars.js

Brand new guide on renewing physical cards

Doc 916/renew physical cards

---

docs/topics/cards/virtual/index.mdx

https://linear.app/swan/issue/DOC-1152/suvcs-default-expiration

DOC-1152: SUVCs one-off default expiration

---

docs/developers/using-api/authentication/guide-get-token-user.mdx

Hey,
I made a minor edit here. Please feel free to review when you have time. 
Thanks.

DOC-1133 Edit sub of user access token

---

docs/topics/accounts/memberships/index.mdx

Added the conditions for when `restrictedTo.birthDate` is required.

Doc 1141/restricted birthdate conditions

---

changelog/2025/2025-07-31.mdx
changelog/2025/2025-08-01.mdx
changelog/coming-up.mdx

https://github.com/swan-io/docs/compare/DOC-1189/cycle-4-changelog?expand=1

Doc 1189/cycle 4 changelog

---

docs/topics/merchants/online/sdd/guide-declare.mdx
docs/topics/merchants/online/sdd/index.mdx
docs/topics/payments/direct-debit/index.mdx

Hey,
Added UMR + SCI uniqueness note to Incoming SDD docs and mandate guide for consistency with Outgoing SDD.

Doc 1107/add umr sci info

---

docs/topics/cards/physical/guide-block-unblock.mdx
docs/topics/merchants/online/index.mdx
docs/topics/merchants/online/sdd/guide-initiate.mdx
docs/topics/merchants/online/sdd/index.mdx

Hey! I've mistakenly merged with the unblocking cards pull request (already published). I hope this won't have an impact. 
Everything else is relevant to this ticket. 
Thanks for the review.

Doc 1247/update merchant sdd docs
